### ISSUE TITLE
Can't bundle woff files

### ISSUE THREAD

**Issue by janat08** [beercss/beercss#239]
I tried rollup, parcel, and esbuild. None of them support woff imports by default. It'd be nice for install instructions to include the workaround necessary to get beercss bundled, or provide alternate install way that has woff files just linked in html.

@parcel/core: No transformers found for
_node_modules/beercss/dist/cdn/material-symbols-sharp.woff2_.

**Comment by leonardorafael** [comment]
Fixed in v3.4.6 (https://github.com/beercss/beercss/releases/tag/v3.4.3)

**Comment by myrp-leonardo** [comment]
Have you tried the latest version v3.4.7, it will not import the .woff2 files anymore.

**Comment by myrp-leonardo** [comment]
@janat08 strange, this works https://codesandbox.io/p/devbox/lucid-rain-4gxknv (using parcel 2)

**Comment by janat08** [comment]
Parcel doesn't work for some of my other packages so I used esbuild.

**Comment by TorH2k3** [comment]
I don't get why this bug has been closed, I'm using the latest versions of beercss and material-dynamic-colors and still get the error "No loader is configured for ".woff2"" when building.
"beercss": "^3.4.7"
"material-dynamic-colors": "^1.1.0"

**Comment by leonardorafael** [comment]
Hi, this issue was closed because this is not a bug in Beer CSS itself. Load font files inside CSS is a web standard. It seems that the bundler need some extra plugin/config to do the job. In my opinion, all bundlers should have to follow the web standards by default.

I found a possible solution here (making .woff and .woff2 files as external)?
https://github.com/evanw/esbuild/issues/800

Let me know if this works for you, please.

**Comment by tmutton** [comment]
If, like me, you've suffered the same problem; please read this angular cli PR - https://github.com/angular/angular-cli/pull/26371 which was released as part of the 17.1.0 version.

The fix for this problem is to add the following option in your angular.json file

```
"loader": {
              ".woff2": "file"
            }
```

This should sit under architect > build > options
